### ISSUE TITLE
doubleQuotes option is back to front

### ISSUE THREAD

**Issue by axefrog** [escaya/escaya-codegen#6]
The implementation works fine, but applies the wrong value. `true` produces single quotes and vice versa.

**Comment by KFlash** [comment]
Than for the info. I will swap it around soon

**Comment by KFlash** [comment]
@axefrog  Look at this tests. I didn't get what's wrong with that option? `{ doubleQuotes: false }` forced single quotes.

https://github.com/escaya/escaya-codegen/blob/master/test/strings.ts

**Comment by axefrog** [comment]
This is what I'm getting. Code as follows:

```js
const ast = Escaya.parseModule(`console.log('Hello');`);
console.log(ECG.generate(ast, { doubleQuotes: true }));
console.log(ECG.generate(ast, { doubleQuotes: false }));
```

Output:

```sh
console.log('Hello')   # (doubleQuotes: true)
console.log("Hello")   # (doubleQuotes: false)
```

- escaya-codegen package version is 0.0.13
- escaya package version is 0.0.51

**Comment by KFlash** [comment]
Ok. Seems like we are getting different results. I changed the entire option now to `singleQuotes`. Let's see if that solve this issue.

v. 0.0.14 is on NPM

**Comment by axefrog** [comment]
Will do. Also I updated escaya to 0.0.54 to see if that was the issue, but didn't affect things. I'll update codegen now.

**Comment by KFlash** [comment]
Escaya 0.0.54 is all about comment extraction. Nothing related to this issue.

**Comment by axefrog** [comment]
Hmm, weird, the issue is still there:

```js
const ast = Escaya.parseModule(`console.log('Hello');`);
console.log(ECG.generate(ast, { singleQuotes: true }));
console.log(ECG.generate(ast, { singleQuotes: false }));
```

```
console.log("Hello")
console.log('Hello')
```

**Comment by axefrog** [comment]
Side note, and not sure if by design, but I can't import the individual functions from Escaya. There is one default export and all functions are bundled into an object there.

**Comment by KFlash** [comment]
This is super weird. Look at this test cases. The option works as it should.

https://github.com/escaya/escaya-codegen/blob/master/test/strings.ts

**Comment by axefrog** [comment]
Maybe try dumping my code into a script in a throwaway directory and npm installing escaya and escaya-codegen (to make sure it's a clean end-user experience). I'd be curious if it's something I'm doing wrong ... though the example seems simple enough that I can't imagine what the issue might be...

**Comment by axefrog** [comment]
I'll do a fresh install of escaya and escaya-codegen too, just in case something weird happened on my end...?

**Comment by KFlash** [comment]
I figures it out. It's NodeJS that doesn't see the differences or don't care what is what. Try latest on NPM, and use `doubleQuotes`

**Comment by axefrog** [comment]
Yep just tried, and it's working now. Thanks for your help!
